import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

ThemeData lightTheme = ThemeData(
  brightness: Brightness.light,
  textTheme: GoogleFonts.josefinSansTextTheme(),
  colorScheme:   const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff525a92),
      surfaceTint: Color(0xff525a92),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffdee0ff),
      onPrimaryContainer: Color(0xff0b154b),
      secondary: Color(0xff5b5d72),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffe0e1f9),
      onSecondaryContainer: Color(0xff181a2c),
      tertiary: Color(0xff77536d),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffffd7f1),
      onTertiaryContainer: Color(0xff2d1228),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff410002),
      surface: Color(0xfffbf8ff),
      onSurface: Color(0xff1b1b21),
      onSurfaceVariant: Color(0xff46464f),
      outline: Color(0xff767680),
      outlineVariant: Color(0xffc7c5d0),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff303036),
      inversePrimary: Color(0xffbbc3ff),
      primaryFixed: Color(0xffdee0ff),
      onPrimaryFixed: Color(0xff0b154b),
      primaryFixedDim: Color(0xffbbc3ff),
      onPrimaryFixedVariant: Color(0xff3a4379),
      secondaryFixed: Color(0xffe0e1f9),
      onSecondaryFixed: Color(0xff181a2c),
      secondaryFixedDim: Color(0xffc3c5dd),
      onSecondaryFixedVariant: Color(0xff434559),
      tertiaryFixed: Color(0xffffd7f1),
      onTertiaryFixed: Color(0xff2d1228),
      tertiaryFixedDim: Color(0xffe6bad7),
      onTertiaryFixedVariant: Color(0xff5d3c55),
      surfaceDim: Color(0xffdbd9e0),
      surfaceBright: Color(0xfffbf8ff),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff5f2fa),
      surfaceContainer: Color(0xffefedf4),
      surfaceContainerHigh: Color(0xffe9e7ef),
      surfaceContainerHighest: Color(0xffe4e1e9),
    )
);

ThemeData darkTheme = ThemeData(
  brightness: Brightness.dark,
  textTheme: GoogleFonts.josefinSansTextTheme(),
  colorScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffbbc3ff),
      surfaceTint: Color(0xffbbc3ff),
      onPrimary: Color(0xff232c61),
      primaryContainer: Color(0xff3a4379),
      onPrimaryContainer: Color(0xffdee0ff),
      secondary: Color(0xffc3c5dd),
      onSecondary: Color(0xff2d2f42),
      secondaryContainer: Color(0xff434559),
      onSecondaryContainer: Color(0xffe0e1f9),
      tertiary: Color(0xffe6bad7),
      onTertiary: Color(0xff44263d),
      tertiaryContainer: Color(0xff5d3c55),
      onTertiaryContainer: Color(0xffffd7f1),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff121318),
      onSurface: Color(0xffe4e1e9),
      onSurfaceVariant: Color(0xffc7c5d0),
      outline: Color(0xff90909a),
      outlineVariant: Color(0xff46464f),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe4e1e9),
      inversePrimary: Color(0xff525a92),
      primaryFixed: Color(0xffdee0ff),
      onPrimaryFixed: Color(0xff0b154b),
      primaryFixedDim: Color(0xffbbc3ff),
      onPrimaryFixedVariant: Color(0xff3a4379),
      secondaryFixed: Color(0xffe0e1f9),
      onSecondaryFixed: Color(0xff181a2c),
      secondaryFixedDim: Color(0xffc3c5dd),
      onSecondaryFixedVariant: Color(0xff434559),
      tertiaryFixed: Color(0xffffd7f1),
      onTertiaryFixed: Color(0xff2d1228),
      tertiaryFixedDim: Color(0xffe6bad7),
      onTertiaryFixedVariant: Color(0xff5d3c55),
      surfaceDim: Color(0xff121318),
      surfaceBright: Color(0xff39393f),
      surfaceContainerLowest: Color(0xff0d0e13),
      surfaceContainerLow: Color(0xff1b1b21),
      surfaceContainer: Color(0xff1f1f25),
      surfaceContainerHigh: Color(0xff29292f),
      surfaceContainerHighest: Color(0xff34343a),
    )
);
